### PR TITLE
support GPU inference in torchscript

### PR DESCRIPTION
**Pull request by taoleicn**
**This is on 3.0.0-dev branch for now**

A non-trivial PR to support GPU inference in torchscript
- Load CUDA kernels as non-python modules; this is needed for torchscript compilation
- Refactored CUDA APIs as functions that return output as tensors, instead of procedures that modify some passed-in tensors.
- Added a workaround in case TS tries to locate and compile CUDA methods on machines that don't have CUDA / GPUs

The refactored code has passed the forward() & backward() test.
I also checked the outputs are the same for the non-torchscript and torchscript versions of the same model.

### CODE REVIEW

**Comment by taoleicn** [comment]
@cdfox-asapp @hpasapp

**Comment by hpasapp** [comment]
cool. tests? (gpu tests wont run on CCIE, but we can at least run them by hand)

**Comment by hpasapp** [comment]
Note that hte following failures occur if I run `pytest -v test` by hand on a gpu instance:

```
====================================================================================== short test summary info =======================================================================================
FAILED test/sru/test_torchscript.py::test_srupp[1-1-False-2-False] - RuntimeError:
FAILED test/sru/test_torchscript.py::test_srupp[1-1-False-2-True] - RuntimeError:
FAILED test/sru/test_torchscript.py::test_srupp[1-1-False-4-False] - RuntimeError:
FAILED test/sru/test_torchscript.py::test_srupp[1-1-False-4-True] - RuntimeError:
FAILED test/sru/test_torchscript.py::test_srupp[1-1-True-2-False] - RuntimeError: Can't redefine method: forward on class: __torch__.sru.modules.SRUppAttention (of Python compilation unit at: 0x5...
FAILED test/sru/test_torchscript.py::test_srupp[1-1-True-2-True] - RuntimeError: Can't redefine method: forward on class: __torch__.sru.modules.___torch_mangle_69.SRUppAttention (of Python compil...
FAILED test/sru/test_torchscript.py::test_srupp[1-1-True-4-False] - RuntimeError: Can't redefine method: forward on class: __torch__.sru.modules.___torch_mangle_79.SRUppAttention (of Python compi...
FAILED test/sru/test_torchscript.py::test_srupp[1-1-True-4-True] - RuntimeError: Can't redefine method: forward on class: __torch__.sru.modules.___torch_mangle_83.SRUppAttention (of Python compil...
FAILED test/sru/test_torchscript.py::test_srupp[1-2-False-2-False] - RuntimeError:
FAILED test/sru/test_torchscript.py::test_srupp[1-2-False-2-True] - RuntimeError:
FAILED test/sru/test_torchscript.py::test_srupp[1-2-False-4-False] - RuntimeError:
FAILED test/sru/test_torchscript.py::test_srupp[1-2-False-4-True] - RuntimeError:
FAILED test/sru/test_torchscript.py::test_srupp[1-2-True-2-False] - RuntimeError: Can't redefine method: forward on class: __torch__.sru.modules.___torch_mangle_93.SRUppAttention (of Python compi...
FAILED test/sru/test_torchscript.py::test_srupp[1-2-True-2-True] - RuntimeError: Can't redefine method: forward on class: __torch__.sru.modules.___torch_mangle_97.SRUppAttention (of Python compil...
FAILED test/sru/test_torchscript.py::test_srupp[1-2-True-4-False] - RuntimeError: Can't redefine method: forward on class: __torch__.sru.modules.___torch_mangle_103.SRUppAttention (of Python comp...
FAILED test/sru/test_torchscript.py::test_srupp[1-2-True-4-True] - RuntimeError: Can't redefine method: forward on class: __torch__.sru.modules.___torch_mangle_107.SRUppAttention (of Python compi...
FAILED test/sru/test_torchscript.py::test_srupp[1-3-False-2-False] - RuntimeError: Can't redefine method: forward on class: __torch__.sru.modules.___torch_mangle_93.SRUppAttention (of Python comp...
FAILED test/sru/test_torchscript.py::test_srupp[1-3-False-2-True] - RuntimeError: Can't redefine method: forward on class: __torch__.sru.modules.___torch_mangle_97.SRUppAttention (of Python compi...
FAILED test/sru/test_torchscript.py::test_srupp[1-3-False-4-False] - RuntimeError: Can't redefine method: forward on class: __torch__.sru.modules.___torch_mangle_103.SRUppAttention (of Python com...
FAILED test/sru/test_torchscript.py::test_srupp[1-3-False-4-True] - RuntimeError: Can't redefine method: forward on class: __torch__.sru.modules.___torch_mangle_107.SRUppAttention (of Python comp...
FAILED test/sru/test_torchscript.py::test_srupp[1-3-True-2-False] - RuntimeError: Can't redefine method: forward on class: __torch__.sru.modules.___torch_mangle_93.SRUppAttention (of Python compi...
FAILED test/sru/test_torchscript.py::test_srupp[1-3-True-2-True] - RuntimeError: Can't redefine method: forward on class: __torch__.sru.modules.___torch_mangle_97.SRUppAttention (of Python compil...
FAILED test/sru/test_torchscript.py::test_srupp[1-3-True-4-False] - RuntimeError: Can't redefine method: forward on class: __torch__.sru.modules.___torch_mangle_103.SRUppAttention (of Python comp...
FAILED test/sru/test_torchscript.py::test_srupp[1-3-True-4-True] - RuntimeError: Can't redefine method: forward on class: __torch__.sru.modules.___torch_mangle_107.SRUppAttention (of Python compi...
FAILED test/sru/test_torchscript.py::test_srupp[2-1-False-2-False] - RuntimeError: Can't redefine method: forward on class: __torch__.sru.modules.SRUppAttention (of Python compilation unit at: 0x...
FAILED test/sru/test_torchscript.py::test_srupp[2-1-False-2-True] - RuntimeError:
FAILED test/sru/test_torchscript.py::test_srupp[2-1-False-4-False] - RuntimeError: Can't redefine method: forward on class: __torch__.sru.modules.___torch_mangle_79.SRUppAttention (of Python comp...
FAILED test/sru/test_torchscript.py::test_srupp[2-1-False-4-True] - RuntimeError:
FAILED test/sru/test_torchscript.py::test_srupp[2-1-True-2-False] - RuntimeError: Can't redefine method: forward on class: __torch__.sru.modules.SRUppAttention (of Python compilation unit at: 0x5...
FAILED test/sru/test_torchscript.py::test_srupp[2-1-True-2-True] - RuntimeError: Can't redefine method: forward on class: __torch__.sru.modules.___torch_mangle_73.SRUppAttention (of Python compil...
FAILED test/sru/test_torchscript.py::test_srupp[2-1-True-4-False] - RuntimeError: Can't redefine method: forward on class: __torch__.sru.modules.___torch_mangle_79.SRUppAttention (of Python compi...
FAILED test/sru/test_torchscript.py::test_srupp[2-1-True-4-True] - RuntimeError: Can't redefine method: forward on class: __torch__.sru.modules.___torch_mangle_85.SRUppAttention (of Python compil...
FAILED test/sru/test_torchscript.py::test_srupp[2-2-False-2-False] - RuntimeError: Can't redefine method: forward on class: __torch__.sru.modules.___torch_mangle_93.SRUppAttention (of Python comp...
FAILED test/sru/test_torchscript.py::test_srupp[2-2-False-2-True] - RuntimeError:
FAILED test/sru/test_torchscript.py::test_srupp[2-2-False-4-False] - RuntimeError: Can't redefine method: forward on class: __torch__.sru.modules.___torch_mangle_103.SRUppAttention (of Python com...
FAILED test/sru/test_torchscript.py::test_srupp[2-2-False-4-True] - RuntimeError:
FAILED test/sru/test_torchscript.py::test_srupp[2-2-True-2-False] - RuntimeError: Can't redefine method: forward on class: __torch__.sru.modules.___torch_mangle_93.SRUppAttention (of Python compi...
FAILED test/sru/test_torchscript.py::test_srupp[2-2-True-2-True] - RuntimeError: Can't redefine method: forward on class: __torch__.sru.modules.___torch_mangle_99.SRUppAttention (of Python compil...
FAILED test/sru/test_torchscript.py::test_srupp[2-2-True-4-False] - RuntimeError: Can't redefine method: forward on class: __torch__.sru.modules.___torch_mangle_103.SRUppAttention (of Python comp...
FAILED test/sru/test_torchscript.py::test_srupp[2-2-True-4-True] - RuntimeError: Can't redefine method: forward on class: __torch__.sru.modules.___torch_mangle_109.SRUppAttention (of Python compi...
FAILED test/sru/test_torchscript.py::test_srupp[2-3-False-2-False] - RuntimeError: Can't redefine method: forward on class: __torch__.sru.modules.___torch_mangle_93.SRUppAttention (of Python comp...
FAILED test/sru/test_torchscript.py::test_srupp[2-3-False-2-True] - RuntimeError: Can't redefine method: forward on class: __torch__.sru.modules.___torch_mangle_99.SRUppAttention (of Python compi...
FAILED test/sru/test_torchscript.py::test_srupp[2-3-False-4-False] - RuntimeError: Can't redefine method: forward on class: __torch__.sru.modules.___torch_mangle_103.SRUppAttention (of Python com...
FAILED test/sru/test_torchscript.py::test_srupp[2-3-False-4-True] - RuntimeError: Can't redefine method: forward on class: __torch__.sru.modules.___torch_mangle_109.SRUppAttention (of Python comp...
FAILED test/sru/test_torchscript.py::test_srupp[2-3-True-2-False] - RuntimeError: Can't redefine method: forward on class: __torch__.sru.modules.___torch_mangle_93.SRUppAttention (of Python compi...
FAILED test/sru/test_torchscript.py::test_srupp[2-3-True-2-True] - RuntimeError: Can't redefine method: forward on class: __torch__.sru.modules.___torch_mangle_99.SRUppAttention (of Python compil...
FAILED test/sru/test_torchscript.py::test_srupp[2-3-True-4-False] - RuntimeError: Can't redefine method: forward on class: __torch__.sru.modules.___torch_mangle_103.SRUppAttention (of Python comp...
FAILED test/sru/test_torchscript.py::test_srupp[2-3-True-4-True] - RuntimeError: Can't redefine method: forward on class: __torch__.sru.modules.___torch_mangle_109.SRUppAttention (of Python compi...
====================================================================== 48 failed, 42 passed, 1 skipped, 301 warnings in 16.04s =====================================================================
```
(not sure if this is specific to this PR, or more general to 3.0.0-dev branch?)

**Comment by hpasapp** [comment]
(on `master` these tests pass, on `3.0.0-dev` they do not)

**Comment by taoleicn** [comment]
@hpasapp Do you think we can merge in the PR w/o resolving the pytorch 1.8 issue?
I'm not sure if it is a pytorch issue.

**Comment by hpasapp** [comment]
we should at least document that we dont support torch > 1.7 I feel?

**Comment by hpasapp** [comment]
pushed a commit for that. thoughts?

**Review by hpasapp — APPROVED** [review]

**Comment by taoleicn** [comment]
@hpasapp looks good. Thank you. 

We can address the compatibility issue with py 1.8 in separate PRs perhaps. to avoid this PR getting too big.

**Pull request merged**
